#!/bin/bash
# Deploy do logo invertido do Skylift na EC2

echo "==========================================="
echo "🚀 DEPLOY - Skylift Logo Update"
echo "==========================================="
echo ""
echo "📋 O que será feito:"
echo "   - Pull do código atualizado (com novo logo)"
echo "   - Rebuild do frontend public-page"
echo "   - Restart do nginx"
echo ""
echo "==========================================="
echo "COMANDOS PARA EXECUTAR NA EC2:"
echo "==========================================="
echo ""
echo "# 1. Conectar na EC2:"
echo "ssh ubuntu@<IP_DA_EC2>"
echo ""
echo "# 2. Ir para o diretório do projeto:"
echo "cd /opt/statuspage"
echo ""
echo "# 3. Atualizar código:"
echo "git pull origin master"
echo ""
echo "# 4. Rebuild do frontend public-page:"
echo "cd /opt/statuspage/frontend/public-page"
echo "npm run build"
echo ""
echo "# 5. Restart do nginx:"
echo "sudo systemctl restart nginx"
echo ""
echo "# 6. Limpar cache do navegador ou fazer hard refresh (Ctrl+Shift+R)"
echo ""
echo "==========================================="
echo "✅ Após executar, acesse:"
echo "   https://status.piercloud.com/"
echo "==========================================="
