#!/bin/bash
# COMANDOS PARA EXECUTAR MANUALMENTE

echo "=========================================="
echo "📋 PASSO A PASSO - DEPLOY MANUAL"
echo "=========================================="
echo ""
echo "✅ Commit já foi feito localmente!"
echo ""
echo "=========================================="
echo "PASSO 1: PUSH (Execute no seu terminal)"
echo "=========================================="
echo ""
echo "cd /Users/milleno/Documents/status/statuspage"
echo "git push origin master"
echo ""
echo "# Se pedir autenticação, use suas credenciais do GitHub"
echo ""
echo "=========================================="
echo "PASSO 2: CONECTAR NA EC2"
echo "=========================================="
echo ""
echo "ssh ubuntu@<SEU_IP_EC2>"
echo ""
echo "=========================================="
echo "PASSO 3: ATUALIZAR CÓDIGO NA EC2"
echo "=========================================="
echo ""
echo "cd /opt/statuspage"
echo "git pull origin master"
echo ""
echo "=========================================="
echo "PASSO 4: EXECUTAR DEPLOY AUTOMATIZADO"
echo "=========================================="
echo ""
echo "bash deploy-lighthouse-grouping.sh"
echo ""
echo "# O script vai:"
echo "# 1. Aplicar migrations no banco"
echo "# 2. Verificar serviços que serão agrupados"
echo "# 3. Recompilar backend Go"
echo "# 4. Reiniciar backend"
echo "# 5. Calcular uptime inicial do grupo"
echo "# 6. Configurar cron job"
echo "# 7. Verificar status final"
echo ""
echo "=========================================="
echo "PASSO 5: VERIFICAR SE FUNCIONOU"
echo "=========================================="
echo ""
echo "# Verificar grupo criado:"
echo "cd /opt/statuspage"
echo "source backend/.env"
echo ""
echo 'PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "'
echo "SELECT sg.display_name, COUNT(sgm.service_id) as total_services"
echo "FROM service_groups sg"
echo "LEFT JOIN service_group_members sgm ON sg.id = sgm.group_id"
echo "WHERE sg.name = 'lighthouse'"
echo 'GROUP BY sg.display_name;"'
echo ""
echo "# Deve mostrar: LIGHTHOUSE | 7"
echo ""
echo "# Testar script manualmente:"
echo "python3 update-group-uptime.py"
echo ""
echo "# Verificar página pública:"
echo "# https://statuspage.piercloud.io/"
echo ""
echo "=========================================="
echo "✅ PRONTO!"
echo "=========================================="
