#!/bin/bash
# GUIA RÁPIDO - Deploy Agrupamento LIGHTHOUSE

echo "=========================================="
echo "📋 GUIA RÁPIDO DE DEPLOY"
echo "=========================================="
echo ""
echo "🎯 OBJETIVO:"
echo "   Agrupar serviços (LOGIN, WEBSOCKET, LAKE, LIGHTHOUSE-BACKEND,"
echo "   DATA, NLB-KONG, AUTH) em um único card LIGHTHOUSE no modo uptime"
echo ""
echo "=========================================="
echo "PASSO 1: COMMIT (Local)"
echo "=========================================="
echo ""
echo "cd /Users/milleno/Documents/status/statuspage"
echo "git add ."
echo "git commit -m 'feat: Implementa agrupamento LIGHTHOUSE para uptime agregado'"
echo "git push origin main"
echo ""
echo "=========================================="
echo "PASSO 2: DEPLOY (EC2)"
echo "=========================================="
echo ""
echo "ssh ubuntu@<IP_DA_EC2>"
echo "cd /opt/statuspage"
echo "git pull origin main"
echo "bash deploy-lighthouse-grouping.sh"
echo ""
echo "=========================================="
echo "PASSO 3: VERIFICAR"
echo "=========================================="
echo ""
echo "# Verificar grupo criado:"
echo "cd /opt/statuspage"
echo "source backend/.env"
echo "PGPASSWORD=\$DB_PASSWORD psql -h \$DB_HOST -U \$DB_USER -d \$DB_NAME -c \\"
echo "  \"SELECT sg.display_name, COUNT(sgm.service_id) as total_services"
echo "   FROM service_groups sg"
echo "   LEFT JOIN service_group_members sgm ON sg.id = sgm.group_id"
echo "   WHERE sg.name = 'lighthouse'"
echo "   GROUP BY sg.display_name;\""
echo ""
echo "# Testar script:"
echo "python3 update-group-uptime.py"
echo ""
echo "# Verificar página:"
echo "https://statuspage.piercloud.io/"
echo ""
echo "=========================================="
echo "✅ PRONTO!"
echo "=========================================="
